runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

handlers:
- url: style.css
  static_files: style.css
  upload: style.css

- url: /(.*)
  static_files: /\1
  upload: /(.*)